name: Tailscale Test

on:
  push:
    branches:
      - '*'

  pull_request:
      branches:
        - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: 1

      - name: status
        run: tailscale status